// Supabase database type definitions
// These will be auto-generated by Supabase CLI in production
// For now, using a placeholder structure

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          username: string
          avatar_url: string | null
          rating: number
          verified: boolean
          successful_sales: number
          created_at: string
        }
        Insert: {
          id: string
          username: string
          avatar_url?: string | null
          rating?: number
          verified?: boolean
          successful_sales?: number
          created_at?: string
        }
        Update: {
          id?: string
          username?: string
          avatar_url?: string | null
          rating?: number
          verified?: boolean
          successful_sales?: number
          created_at?: string
        }
      }
      events: {
        Row: {
          id: string
          artist: string
          title: string
          venue: string
          city: string
          event_date: string
          image_url: string | null
          created_at: string
        }
        Insert: {
          id?: string
          artist: string
          title: string
          venue: string
          city: string
          event_date: string
          image_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          artist?: string
          title?: string
          venue?: string
          city?: string
          event_date?: string
          image_url?: string | null
          created_at?: string
        }
      }
      tickets: {
        Row: {
          id: string
          seller_id: string
          event_id: string
          section: string | null
          row: string | null
          seat: string | null
          quantity: number
          price: number
          proof_url: string | null
          status: 'available' | 'locked' | 'sold' | 'flagged'
          created_at: string
        }
        Insert: {
          id?: string
          seller_id: string
          event_id: string
          section?: string | null
          row?: string | null
          seat?: string | null
          quantity: number
          price: number
          proof_url?: string | null
          status?: 'available' | 'locked' | 'sold' | 'flagged'
          created_at?: string
        }
        Update: {
          id?: string
          seller_id?: string
          event_id?: string
          section?: string | null
          row?: string | null
          seat?: string | null
          quantity?: number
          price?: number
          proof_url?: string | null
          status?: 'available' | 'locked' | 'sold' | 'flagged'
          created_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          buyer_id: string
          ticket_id: string
          total: number
          payment_intent: string | null
          status: 'pending' | 'paid' | 'delivered' | 'completed' | 'refunded' | 'disputed'
          created_at: string
        }
        Insert: {
          id?: string
          buyer_id: string
          ticket_id: string
          total: number
          payment_intent?: string | null
          status?: 'pending' | 'paid' | 'delivered' | 'completed' | 'refunded' | 'disputed'
          created_at?: string
        }
        Update: {
          id?: string
          buyer_id?: string
          ticket_id?: string
          total?: number
          payment_intent?: string | null
          status?: 'pending' | 'paid' | 'delivered' | 'completed' | 'refunded' | 'disputed'
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
